### ISSUE TITLE
image files are deleted after pdf has been rendered

### ISSUE THREAD

**Issue by BigMichi1** [tecnickcom/TCPDF#158]
hello,

we have a serious issue since the update to version 6.3.0. we have two static images that we include in the header. when the pdf is rendered they are deleted from the filesystem. so every new pdf does not have these files anymore. i tracked this down to this commit: https://github.com/tecnickcom/TCPDF/commit/b41a5ca3114c18214ec2871fb68923e6d7bb9e92

the images are added in this way:

    $this->resourceDirectory = getcwd() . '/data/content/';
    $this->Image($this->resourceDirectory . 'image.png', 371, 60, 164, 60, '', '', 'T');

and then in _destroy() they are deleted from the filesystem. how can we avoid the deletion of these files?

**Comment by BigMichi1** [comment]
an interesting fact: we have 3 images in the pdf (all as a static resource included) only the first two are deleted from the filesystem, the last one not

**Comment by BigMichi1** [comment]
this is the place when it happens

![Screenshot_20191230_125406](https://user-images.githubusercontent.com/91786/71580994-7ec5a600-2b03-11ea-8c9d-511ed95dac1c.png)

**Comment by GianlucaBergomi** [comment]
I have the same problem!

**Comment by alesak** [comment]
Same issue here

**Comment by NiklasBr** [comment]
Ping @nicolaasuni

**Comment by tlokot** [comment]
This loop is causing the same problem for me in the _destroy method:

			if (isset($this->imagekeys)) {
				foreach($this->imagekeys as $file) {
					unlink($file);
				}
			}

**Comment by BigMichi1** [comment]
with this snippet i'm currently workaround this bug, maybe it helps others. 
    
    class MyPdf extends TCPDF
        /**
         * @param bool $destroyall
         * @param bool $preserve_objcopy
         */
        public function _destroy($destroyall = false, $preserve_objcopy = false)
        {
            if ($destroyall) {
                unset($this->imagekeys);
            }
            parent::_destroy($destroyall, $preserve_objcopy);
        }
    }

**Comment by rieschl** [comment]
FYI: I discovered that this only happens if I set a non-default font-family (i.e. `$pdf->SetFont('freesans', '', 8);`). I mentioned that in a side note in my issue (#175).

**Comment by nicolaasuni** [comment]
This should be fixed in the latest version.

**Comment by rieschl** [comment]
It still happens for me, but now always and not just with a non-default font-family.

**Comment by nicolaasuni** [comment]
I have pushed another change now.

**Comment by NiklasBr** [comment]
Thanks for all the merges and the new release @nicolaasuni !

**Comment by rieschl** [comment]
It works for me now! Thanks for the quick help, @nicolaasuni !

**Comment by Jaafarnasrallah** [comment]
@nicolaasuni thanks a lot! it is now solved

**Comment by Vitalicus** [comment]
Not solved yet? Deleted my background image :(
